package com.schoolErp.entity.admission_lead_crm_automation;

import com.schoolErp.AuditableEntity;
import com.schoolErp.entity.core.User;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

// 3. FollowUpTask (Automation - reminders, WhatsApp/email tasks)
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "follow_up_tasks",
        indexes = @Index(columnList = "due_date, status"))
public class FollowUpTask extends AuditableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "task_seq")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id", nullable = false)
    private Lead lead;

    @ManyToOne
    @JoinColumn(name = "assigned_to_id")
    private User assignedTo;            // Counselor / user

    @NotBlank
    @Size(max = 500)
    private String taskDescription;     // "Call parent about fee concession", "Send brochure PDF"

    @Enumerated(EnumType.STRING)
    private CommunicationChannel preferredChannel; // WHATSAPP, SMS, EMAIL, CALL, IN_PERSON

    @NotNull
    private LocalDateTime dueDateTime;

    @Enumerated(EnumType.STRING)
    private TaskStatus status = TaskStatus.PENDING;

    private LocalDateTime completedAt;

    @Column(columnDefinition = "text")
    private String outcomeNotes;

    // For automation engine to trigger
    private boolean autoGenerated = false;

    // ...
}
